# Generated by Django 4.2.3 on 2023-07-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
